// Per-page content registry. Each entry feeds the LandingPage sections.
// Each page has an `en` block with English overrides (merged over the Dutch base).

const PAGE_DATA = {
  bcorp: {
    key: 'bcorp',
    title: 'B-Corps & ESG-kantoren, Moyee',
    hero: {
      eyebrow: 'B-Corp & ESG-kantoren',
      headline: ['Jij bent gecertificeerd.', 'Je koffie ook.'],
      subline: 'Moyee is de enige koffie die geboerd, geroosterd én verpakt wordt in het productieland. Concreet, traceerbaar, eerlijk. Precies wat jij in je ESG-rapport wilt zien.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep hier een foto van je kantoor / impact-rapport',
    },
    story: {
      heading: 'Van Fairchain naar jouw jaarverslag',
      body: 'B-Corp-certificering vraagt om keuzes in de hele keten, ook in je inkoop. Moyee is gebouwd op dat principe. Elke kilo koffie die jij bestelt, produceert werkgelegenheid, kennis en geld in Ethiopië en Kenia. Niet als donatie, maar als verdienmodel. Dat heet Fairchain.',
      highlight: 'Traditionele koffie wordt elders geroosterd, zodat de marge en kennis achterblijven bij de groothandel. Bij Moyee gebeurt alles in het productieland. Daardoor verdient een Ethiopische of Keniaanse medewerker aan jouw koffie. Dat is geen claim. Het is het businessmodel. En het staat in jouw ESG-rapportage.',
    },
    steps: [
      'Bereken hoeveel koffie jullie team nodig heeft en kies je blend',
      'Koffie wordt geroosterd in Ethiopië of Kenia — direct naar jullie kantoor',
      'Ontvang je Fairchain-impactrapportage: traceerbare data voor je ESG-dossier',
    ],
    testimonials: {
      label: 'Klanten die je herkent',
      heading: 'Organisaties met dezelfde standaard',
      items: [
        {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
          quote:'Voor ons is Moyee geen inkoopdecisie maar een logische keuze. Elke kop koffie vertelt het verhaal van eerlijk ondernemen.'},
        {client:'ASR', logo:'assets/clients/asr.png',
          quote:'We wilden als verzekeraar in onze inkoop aantonen dat duurzaamheid en kwaliteit hand in hand gaan. Moyee is daarin vanzelfsprekend.'},
        {client:'Amnesty International NL',
          quote:'Moyee past bij onze waarden. Niet omdat we het moeten uitleggen, maar omdat het systeem klopt.'},
      ],
    },
    impact: { label: 'Impact per bestelling' },
    cta: {
      heading: 'Klaar om Moyee aan je ESG-dossier toe te voegen?',
      sub: 'Ontvang een proefpakket en een impactoverzicht voor je rapportage.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'B-Corps & ESG offices, Moyee',
      hero: {
        eyebrow: 'B-Corp & ESG offices',
        headline: ["You're certified.", 'Your coffee too.'],
        subline: 'Moyee is the only coffee that is farmed, roasted and packaged in the country of origin. Concrete, traceable, fair. Exactly what you want to see in your ESG report.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office / impact report here',
      },
      story: {
        heading: 'From Fairchain to your annual report',
        body: 'B-Corp certification requires choices throughout the supply chain, including procurement. Moyee is built on that principle. Every kilo of coffee you order generates employment, knowledge and income in Ethiopia and Kenya. Not as a donation, but as a business model. That is called Fairchain.',
        highlight: 'Traditional coffee is roasted elsewhere, so the margin and expertise remain with wholesalers. With Moyee, everything happens in the country of origin. That means an Ethiopian or Kenyan employee earns from your coffee. This is not a claim. It is the business model. And it goes into your ESG report.',
      },
      steps: [
        'Calculate how much coffee your team needs and choose your blend',
        'Coffee is roasted in Ethiopia or Kenya — delivered directly to your office',
        'Receive your Fairchain impact report: traceable data for your ESG dossier',
      ],
      testimonials: {
        label: 'Clients you recognise',
        heading: 'Organisations with the same standard',
        items: [
          {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
            quote:'For us, Moyee is not a procurement decision but a logical choice. Every cup tells the story of fair business.'},
          {client:'ASR', logo:'assets/clients/asr.png',
            quote:'As an insurer, we wanted our procurement to prove that sustainability and quality go hand in hand. Moyee is the obvious answer.'},
          {client:'Amnesty International NL',
            quote:'Moyee fits our values. Not because we have to explain it, but because the system works.'},
        ],
      },
      impact: { label: 'Impact per order' },
      cta: {
        heading: 'Ready to add Moyee to your ESG dossier?',
        sub: 'Receive a trial package and an impact overview for your report.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  tech: {
    key: 'tech',
    title: 'Tech scale-ups & People and Culture, Moyee',
    hero: {
      eyebrow: 'Tech scale-ups & People and Culture',
      headline: ['Je hebt overal over nagedacht.', 'Nu de koffie.'],
      subline: 'Je bouwt een bedrijf waar mensen graag werken. De koffie in de keuken is geen bijzaak. Het is een eerste indruk, elke ochtend opnieuw.',
      ctaPrimary: 'Stuur ons een proefpakket',
      imagePlaceholder: 'Sleep een foto van jullie kantoorkeuken / team',
    },
    story: {
      heading: 'Koffie die je team iets te vertellen heeft',
      body: 'Moyee is gebouwd op een idee dat je team waarschijnlijk direct begrijpt: wat als de keten eerlijk is van begin tot eind? Niet als uitzondering, maar als businessmodel. Dat verhaal gaat rond op kantoor. Niet omdat je het uitlegt, maar omdat het op de verpakking staat.',
      highlight: 'Fairchain betekent: geboerd, geroosterd en verpakt in het productieland. Minder tussenschakels, meer waarde voor de mensen achter de boon. Elke kop koffie die jouw team drinkt, is het bewijs dat het anders kan. Dat is het soort detail dat bij mensen blijft.',
    },
    steps: [
      'Bereken hoeveel koffie jullie team verbruikt — de calculator doet het werk',
      'Kies een blend die past bij hoe jullie werken: sterk voor lange dagen, licht voor de loop',
      'Maandelijkse levering aan kantoor. Geen gedoe, geen nadenken',
    ],
    testimonials: {
      label: 'Bedrijven die je kent',
      heading: 'Scale-ups die al voor Moyee kozen',
      items: [
        {client:'Dynalogic', logo:'assets/clients/dynalogic.png',
          quote:'Onze keuken is de plek waar alles begint. Nu begint het met koffie die ergens voor staat.'},
        {client:'Highberg Digital',
          quote:'Nieuw teamlid vroeg meteen waar de koffie vandaan komt. Dat is precies de reden waarom we Moyee hebben.'},
        {client:'Rapid Circle',
          quote:'Fijn dat het gewoon geregeld is. En dat er ook nog iets achter zit.'},
      ],
    },
    impact: { label: 'Impact per bestelling' },
    cta: {
      heading: 'Stuur je team een proefpakket.',
      sub: 'Geen verplichtingen. Wel een verhaal voor in de keuken.',
      primary: 'Stuur ons een proefpakket',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Tech scale-ups & People and Culture, Moyee',
      hero: {
        eyebrow: 'Tech scale-ups & People and Culture',
        headline: ["You've thought of everything.", 'Now the coffee.'],
        subline: "You're building a company people love to work at. The coffee in the kitchen is not a side issue. It's a first impression, every morning.",
        ctaPrimary: 'Send us a trial package',
        imagePlaceholder: 'Drop a photo of your office kitchen / team here',
      },
      story: {
        heading: 'Coffee your team has something to talk about',
        body: "Moyee is built on an idea your team will probably understand right away: what if the supply chain is fair from start to finish? Not as an exception, but as a business model. That story spreads around the office. Not because you explain it, but because it says so on the packaging.",
        highlight: 'Fairchain means: farmed, roasted and packaged in the country of origin. Fewer intermediaries, more value for the people behind the bean. Every cup your team drinks is proof that it can be different. That is the kind of detail that sticks.',
      },
      steps: [
        'Calculate how much coffee your team uses — the calculator does the work',
        'Choose a blend that fits how you work: strong for long days, light for the flow',
        'Monthly delivery to the office. No hassle, no thinking',
      ],
      testimonials: {
        label: 'Companies you know',
        heading: 'Scale-ups that already chose Moyee',
        items: [
          {client:'Dynalogic', logo:'assets/clients/dynalogic.png',
            quote:'Our kitchen is where everything starts. Now it starts with coffee that stands for something.'},
          {client:'Highberg Digital',
            quote:'New team member immediately asked where the coffee comes from. That is exactly why we have Moyee.'},
          {client:'Rapid Circle',
            quote:'Great that it is just sorted. And that there is something behind it too.'},
        ],
      },
      impact: { label: 'Impact per order' },
      cta: {
        heading: 'Send your team a trial package.',
        sub: 'No commitments. But there is a story for the kitchen.',
        primary: 'Send us a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  creative: {
    key: 'creative',
    title: 'Creatieve agencies, Moyee',
    hero: {
      eyebrow: 'Creatieve agencies',
      headline: ['Jullie verkopen verhalen.', 'Dit is er een goeie.'],
      subline: 'Moyee heeft het systeem achter koffie volledig omgedraaid. Van boer tot beker, alles anders. Precies het soort verhaal waar jullie van houden.',
      ctaPrimary: 'Bestel een proefpakket',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie studio',
    },
    story: {
      heading: 'Een merk dat staat voor iets — net als jullie',
      body: 'Wij noemen het Fairchain. Geen marketingterm, maar een model. We kopen niet van de keten. We zijn de keten. Geboerd, geroosterd en verpakt in Ethiopië en Kenia. De designers, roosters en logistici daar verdienen eerlijk. En jij krijgt koffie met een verhaal dat je zelf niet beter had kunnen verzinnen.',
      highlight: 'Goede bureaus weten: het product is het verhaal. Bij Moyee is het omgekeerde ook waar. Het verhaal is het product. Elke verpakking, elke kop, elke levering draagt het systeem dat eerlijk is. Niet als toevoeging, maar als kern. Dat herkennen jullie.',
    },
    steps: [
      'Kies een blend die past bij de sfeer van jullie kantoor',
      'Levering aan jullie studio — maandelijks, geen gedoe',
      "Zet Moyee neer als statement — op tafel bij de klant, op de foto, op jullie kanalen",
    ],
    testimonials: {
      label: 'Studios en bureaus die al voor Moyee kozen',
      heading: 'Bureaus die het verhaal verstaan',
      items: [
        {client:'Pllek Amsterdam',
          quote:'Gasten vragen er altijd naar. Dat is het beste compliment dat je kunt krijgen voor een koffiekeuze.'},
        {client:'Conscious Hotel',
          quote:'Moyee past bij hoe we over alles nadenken. Niet als toevoeging, maar als standaard.'},
        {client:'Brood Café',
          quote:'We hadden iets nodig met een eigen verhaal. Moyee heeft dat, en het smaakt ook nog eens goed.'},
      ],
    },
    impact: { label: 'De getallen achter het verhaal' },
    cta: {
      heading: 'Een proefpakket zegt meer dan een pitch.',
      sub: 'Laat het verhaal voor zichzelf spreken. Wij sturen het op.',
      primary: 'Bestel een proefpakket',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Creative agencies, Moyee',
      hero: {
        eyebrow: 'Creative agencies',
        headline: ['You sell stories.', 'This is a good one.'],
        subline: 'Moyee has completely flipped the coffee system. From farm to cup, everything different. Exactly the kind of story you love.',
        ctaPrimary: 'Order a trial package',
        imagePlaceholder: 'Drop an atmosphere photo of your studio here',
      },
      story: {
        heading: 'A brand that stands for something — just like you',
        body: "We call it Fairchain. Not a marketing term, but a model. We don't buy from the chain. We are the chain. Farmed, roasted and packaged in Ethiopia and Kenya. The designers, roasters and logistics staff there are paid fairly. And you get coffee with a story you couldn't have invented better yourself.",
        highlight: "Good agencies know: the product is the story. At Moyee, the reverse is also true. The story is the product. Every package, every cup, every delivery carries the system that is fair. Not as an add-on, but at the core. You recognise that.",
      },
      steps: [
        'Choose a blend that fits the atmosphere of your studio',
        'Delivery to your studio — monthly, no hassle',
        'Put Moyee out as a statement — on the table with clients, in photos, on your channels',
      ],
      testimonials: {
        label: 'Studios and agencies that already chose Moyee',
        heading: 'Agencies that get the story',
        items: [
          {client:'Pllek Amsterdam',
            quote:'Guests always ask about it. That is the best compliment you can get for a coffee choice.'},
          {client:'Conscious Hotel',
            quote:"Moyee fits how we think about everything. Not as an add-on, but as the standard."},
          {client:'Brood Café',
            quote:'We needed something with its own story. Moyee has that, and it tastes great too.'},
        ],
      },
      impact: { label: 'The numbers behind the story' },
      cta: {
        heading: 'A trial package says more than a pitch.',
        sub: "Let the story speak for itself. We'll send it over.",
        primary: 'Order a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  professional: {
    key: 'professional',
    title: 'Professional services, Moyee',
    hero: {
      eyebrow: 'Professional services',
      headline: ['Integriteit zit in de details.', 'Inclusief de koffie.'],
      subline: 'Voor kantoren die hoge standaarden gewend zijn, ook voor wat er op tafel staat als de klant binnenkomt.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een foto van jullie kantoor / ontvangst',
    },
    story: {
      heading: 'Koffie die past bij hoe jij je werk doet',
      body: 'Moyee maakt de keten van koffie transparant: traceerbaar, eerlijk beloond, van begin tot eind. Als je elke dag werkt aan eerlijkheid, structuur en kwaliteit voor anderen, past Moyee bij hoe jij je kantoor runt. Niet als statement, maar als logische consequentie.',
      highlight: 'Fairchain is geen label maar een model. Elke kilo koffie wordt geproduceerd, geroosterd en verpakt in het land van herkomst. Geen tussenschakels die de waarde afromen. Eerlijk voor de boer, traceerbaar voor jou, merkbaar in de kop. Dat is het soort keuze waar je geen tweede keer over hoeft na te denken.',
    },
    steps: [
      'Bereken hoeveel koffie jullie kantoor maandelijks verbruikt',
      'Kies een blend — specialty niveau, voor de klant aan tafel en de vergadering erna',
      'Vaste maandlevering. Geen nadenken, geen bestellingen, geen tekort',
    ],
    testimonials: {
      label: 'Kantoren die al voor Moyee kozen',
      heading: 'Kantoren met dezelfde standaard',
      items: [
        {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
          quote:'We wilden iets dat past bij hoe we over verantwoord beleggen denken. Moyee sloot daarop aan.'},
        {client:'AXA', logo:'assets/clients/axa.png',
          quote:'Als internationaal bedrijf letten we op elke keuze. Moyee past bij hoe wij omgaan met kwaliteit én maatschappelijke verantwoordelijkheid.'},
        {client:'BVDV Advocaten',
          quote:'Klanten vragen er soms naar als ze de verpakking zien. Dan kun je even iets vertellen.'},
      ],
    },
    impact: { label: 'De feiten' },
    cta: {
      heading: 'Ontvang een proefpakket voor het kantoor.',
      sub: 'Geen verplichtingen. Gewoon koffie — en een verhaal om bij te bewaren.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Professional services, Moyee',
      hero: {
        eyebrow: 'Professional services',
        headline: ['Integrity is in the details.', 'Including the coffee.'],
        subline: "For offices accustomed to high standards, even in what's on the table when a client walks in.",
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office / reception here',
      },
      story: {
        heading: 'Coffee that fits how you do your work',
        body: 'Moyee makes the coffee supply chain transparent: traceable, fairly compensated, from start to finish. If you work every day on fairness, structure and quality for others, Moyee fits how you run your office. Not as a statement, but as a logical consequence.',
        highlight: 'Fairchain is not a label but a model. Every kilo of coffee is produced, roasted and packaged in the country of origin. No intermediaries skimming the value. Fair for the farmer, traceable for you, noticeable in the cup. That is the kind of choice you do not have to think twice about.',
      },
      steps: [
        'Calculate how much coffee your office uses monthly',
        'Choose a blend — specialty level, for the client at the table and the meeting after',
        'Fixed monthly delivery. No thinking, no orders, no shortage',
      ],
      testimonials: {
        label: 'Offices that already chose Moyee',
        heading: 'Offices with the same standard',
        items: [
          {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
            quote:'We wanted something that fits how we think about responsible investing. Moyee matched that.'},
          {client:'AXA', logo:'assets/clients/axa.png',
            quote:'As an international company we pay attention to every choice. Moyee fits how we handle quality and social responsibility.'},
          {client:'BVDV Advocaten',
            quote:'Clients sometimes ask about it when they see the packaging. Then you can say something.'},
        ],
      },
      impact: { label: 'The facts' },
      cta: {
        heading: 'Receive a trial package for the office.',
        sub: 'No obligations. Just coffee — and a story worth keeping.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  cowork: {
    key: 'cowork',
    title: 'Cowork & flexkantoren, Moyee',
    hero: {
      eyebrow: 'Cowork & flexkantoren',
      headline: ['Jouw leden verwachten het beste.', 'Ook van de koffie.'],
      subline: 'Eén contract, honderden gebruikers. Moyee levert specialty koffie die jouw community iets geeft om over te praten — en een verhaal dat past bij waarom ze hier werken.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie coworkruimte',
    },
    story: {
      heading: 'Koffie die de community bouwt',
      body: 'Een coworkspace is meer dan bureaus en wifi. Het gevoel begint bij de koffie. Moyee brengt specialty kwaliteit én een verhaal dat leden direct herkennen: eerlijk, transparant en gemaakt door mensen die er echt beter van worden. Dat is iets om trots op te zijn — en om te delen.',
      highlight: 'Fairchain betekent dat elke kilo koffie wordt geboerd, geroosterd en verpakt in het productieland. Geen verspilde marge aan tussenschakels. Jij biedt je leden een product dat verhalen opwekt. Dat is het verschil tussen koffie als bijzaak en koffie als deel van je merk.',
    },
    steps: [
      'Bereken hoeveel koffie jouw space maandelijks nodig heeft — we helpen rekenen',
      'Één levering, één factuur — ook bij meerdere vestigingen',
      'Leden vragen ernaar. Dan heb je meteen een gesprek over waarom jij dit bewust kiest',
    ],
    testimonials: {
      label: 'Spaces die al voor Moyee kozen',
      heading: 'Communities die het verschil proeven',
      items: [
        {client:'Spaces Amsterdam',
          quote:'Leden merken de kwaliteit meteen. En als ze vragen waar het vandaan komt, hebben we een goed verhaal.'},
        {client:'B. Amsterdam',
          quote:'In een community draait alles om sfeer en gevoel. Moyee draagt daarin bij — elke dag opnieuw.'},
        {client:'Tribes Utrecht',
          quote:'Het gaat verder dan koffie. Het is een keuze die zegt: we denken na over alles wat we hier neerzetten.'},
      ],
    },
    impact: { label: 'Impact per bestelling' },
    cta: {
      heading: 'Zet Moyee neer in jouw space.',
      sub: 'Vraag een proefpakket aan — wij zorgen voor de rest.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Cowork & flex offices, Moyee',
      hero: {
        eyebrow: 'Cowork & flex offices',
        headline: ['Your members expect the best.', 'Including the coffee.'],
        subline: 'One contract, hundreds of users. Moyee delivers specialty coffee that gives your community something to talk about — and a story that fits why they work here.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop an atmosphere photo of your cowork space here',
      },
      story: {
        heading: 'Coffee that builds community',
        body: 'A coworking space is more than desks and wifi. The feeling starts with the coffee. Moyee brings specialty quality and a story members recognise right away: fair, transparent and made by people who genuinely benefit from it. That is something to be proud of — and to share.',
        highlight: 'Fairchain means every kilo of coffee is farmed, roasted and packaged in the country of origin. No wasted margin on intermediaries. You offer your members a product that sparks conversations. That is the difference between coffee as an afterthought and coffee as part of your brand.',
      },
      steps: [
        'Calculate how much coffee your space needs monthly — we help with the maths',
        'One delivery, one invoice — even across multiple locations',
        'Members ask about it. Then you have a conversation about why you chose this consciously.',
      ],
      testimonials: {
        label: 'Spaces that already chose Moyee',
        heading: 'Communities that taste the difference',
        items: [
          {client:'Spaces Amsterdam',
            quote:'Members notice the quality right away. And when they ask where it comes from, we have a great story.'},
          {client:'B. Amsterdam',
            quote:'In a community everything is about atmosphere and feeling. Moyee contributes to that — every day.'},
          {client:'Tribes Utrecht',
            quote:'It goes beyond coffee. It is a choice that says: we think carefully about everything we put here.'},
        ],
      },
      impact: { label: 'Impact per order' },
      cta: {
        heading: 'Put Moyee in your space.',
        sub: 'Request a trial package — we take care of the rest.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  finance: {
    key: 'finance',
    title: 'Verzekeraars & financiële dienstverleners, Moyee',
    hero: {
      eyebrow: 'Verzekeringen & financiële dienstverlening',
      headline: ['Duurzaam beleggen.', 'Duurzame koffie.'],
      subline: 'Financiële instellingen staan steeds vaker voor de vraag: klopt onze eigen inkoop bij wat we uitdragen? Moyee is de koffie waarbij het antwoord ja is.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een foto van jullie kantoor / boardroom',
    },
    story: {
      heading: 'Inkoop die klopt bij jullie ESG-raamwerk',
      body: 'Banken, verzekeraars en vermogensbeheerders stellen strengere eisen aan hun eigen leveranciers. Moyee voldoet aan die eisen — niet als certificeringsstrategie, maar omdat het businessmodel van begin tot eind traceerbaar en eerlijk is. Van boer tot factuur, alles verantwoord.',
      highlight: 'Fairchain is geen label maar een model. Elke kilo koffie wordt geproduceerd, geroosterd en verpakt in het productieland. De marges blijven in de keten waar ze horen. Jij kunt dat aantonen — in het leveranciersregister, in de jaarrekening, aan toezichthouders.',
    },
    steps: [
      'Bereken jullie verbruik — geschikt voor kleine teams én grote kantoorlocaties',
      'Ontvang een Fairchain-impactoverzicht voor jullie leveranciersdossier',
      'Vaste maandlevering, vaste prijs — geen verrassingen op de factuur',
    ],
    testimonials: {
      label: 'Organisaties die je kent',
      heading: 'Financiële dienstverleners die bewust kozen',
      items: [
        {client:'ASR', logo:'assets/clients/asr.png',
          quote:'We wilden als verzekeraar in onze inkoop aantonen dat duurzaamheid en kwaliteit samengaan. Moyee is daarin vanzelfsprekend.'},
        {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
          quote:'We wilden iets dat past bij hoe we over verantwoord beleggen denken. Moyee sloot daarop aan.'},
        {client:'AXA', logo:'assets/clients/axa.png',
          quote:'Als internationaal bedrijf letten we op elke keuze. Moyee past bij hoe wij omgaan met kwaliteit én maatschappelijke verantwoordelijkheid.'},
      ],
    },
    impact: { label: 'Aantoonbare impact per bestelling' },
    cta: {
      heading: 'Koffie die past in jullie leveranciersdossier.',
      sub: 'Ontvang een proefpakket en een impactoverzicht — geschikt voor ESG-rapportage.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Insurers & financial services, Moyee',
      hero: {
        eyebrow: 'Insurance & financial services',
        headline: ['Sustainable investing.', 'Sustainable coffee.'],
        subline: 'Financial institutions increasingly face the question: does our own procurement match what we stand for? Moyee is the coffee where the answer is yes.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office / boardroom here',
      },
      story: {
        heading: 'Procurement that fits your ESG framework',
        body: 'Banks, insurers and asset managers set increasingly strict requirements on their own suppliers. Moyee meets those requirements — not as a certification strategy, but because the business model is traceable and fair from start to finish. From farm to invoice, everything accountable.',
        highlight: 'Fairchain is not a label but a model. Every kilo of coffee is produced, roasted and packaged in the country of origin. Margins stay in the chain where they belong. You can demonstrate that — in the supplier register, in the annual report, to regulators.',
      },
      steps: [
        'Calculate your usage — suitable for small teams and large office locations',
        'Receive a Fairchain impact overview for your supplier dossier',
        'Fixed monthly delivery, fixed price — no surprises on the invoice',
      ],
      testimonials: {
        label: 'Organisations you know',
        heading: 'Financial services firms that chose consciously',
        items: [
          {client:'ASR', logo:'assets/clients/asr.png',
            quote:'As an insurer, we wanted our procurement to prove that sustainability and quality go hand in hand. Moyee is the obvious answer.'},
          {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
            quote:'We wanted something that fits how we think about responsible investing. Moyee matched that.'},
          {client:'AXA', logo:'assets/clients/axa.png',
            quote:'As an international company we pay attention to every choice. Moyee fits how we handle quality and social responsibility.'},
        ],
      },
      impact: { label: 'Demonstrable impact per order' },
      cta: {
        heading: 'Coffee that fits your supplier dossier.',
        sub: 'Receive a trial package and an impact overview — suitable for ESG reporting.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  horeca: {
    key: 'horeca',
    title: 'Boutique HoReCa, Moyee',
    hero: {
      eyebrow: 'Boutique HoReCa',
      headline: ['Je gasten onthouden de koffie.', 'Geef ze een reden.'],
      subline: 'Voor onafhankelijke cafés, boutique hotels en restaurants die bewust kiezen wat er op tafel staat — en dat verhaal kunnen vertellen.',
      ctaPrimary: 'Bestel een proefpakket',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie zaak',
    },
    story: {
      heading: 'Koffie die onderdeel wordt van jouw verhaal',
      body: 'Boutique horeca onderscheidt zich niet op grootte, maar op karakter. Elke keuze — van meubels tot muziek — vertelt wie je bent. Moyee past in dat plaatje: specialty kwaliteit, een traceerbare herkomst en een systeem dat eerlijk is voor iedereen in de keten. Gasten waarderen dat. En ze komen terug.',
      highlight: 'Fairchain: geboerd, geroosterd en verpakt in Ethiopië of Kenia. Geen tussenhandel, geen onbekende herkomst. Als gast vraag je waar de koffie vandaan komt — als eigenaar kun je het antwoord geven. Dat is het gesprek dat jou onderscheidt van de keten om de hoek.',
    },
    steps: [
      'Kies een blend die past bij jouw zaak — van licht en fruitig tot donker en intens',
      'Levering op jouw planning — per week, per twee weken of maandelijks',
      'Gebruik het verhaal: kaartjes, QR-codes en content krijg je mee van ons',
    ],
    testimonials: {
      label: 'Zaken die al voor Moyee kozen',
      heading: 'Horeca die kwaliteit én verhaal serieus neemt',
      items: [
        {client:'Pllek Amsterdam',
          quote:'Gasten vragen er altijd naar. Dat is het beste compliment dat je kunt krijgen voor een koffiekeuze.'},
        {client:'Conscious Hotel',
          quote:'Moyee past bij hoe we over alles nadenken. Niet als toevoeging, maar als standaard.'},
        {client:'Brood Café',
          quote:'We hadden iets nodig met een eigen verhaal. Moyee heeft dat, en het smaakt ook nog eens goed.'},
      ],
    },
    impact: { label: 'Wat jouw bestelling doet' },
    cta: {
      heading: 'Ontdek of Moyee bij jouw zaak past.',
      sub: 'Bestel een proefpakket — proef het zelf voordat je beslist.',
      primary: 'Bestel een proefpakket',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Boutique HoReCa, Moyee',
      hero: {
        eyebrow: 'Boutique HoReCa',
        headline: ['Your guests remember the coffee.', 'Give them a reason.'],
        subline: 'For independent cafés, boutique hotels and restaurants that consciously choose what goes on the table — and can tell that story.',
        ctaPrimary: 'Order a trial package',
        imagePlaceholder: 'Drop an atmosphere photo of your venue here',
      },
      story: {
        heading: 'Coffee that becomes part of your story',
        body: 'Boutique hospitality differentiates itself not on size, but on character. Every choice — from furniture to music — tells who you are. Moyee fits that picture: specialty quality, a traceable origin and a system that is fair for everyone in the chain. Guests appreciate that. And they come back.',
        highlight: 'Fairchain: farmed, roasted and packaged in Ethiopia or Kenya. No middlemen, no unknown origin. When a guest asks where the coffee comes from — you can answer. That is the conversation that sets you apart from the chain around the corner.',
      },
      steps: [
        'Choose a blend that fits your venue — from light and fruity to dark and intense',
        'Delivery on your schedule — weekly, fortnightly or monthly',
        'Use the story: table cards, QR codes and content come with your order',
      ],
      testimonials: {
        label: 'Venues that already chose Moyee',
        heading: 'Hospitality that takes quality and story seriously',
        items: [
          {client:'Pllek Amsterdam',
            quote:'Guests always ask about it. That is the best compliment you can get for a coffee choice.'},
          {client:'Conscious Hotel',
            quote:"Moyee fits how we think about everything. Not as an add-on, but as the standard."},
          {client:'Brood Café',
            quote:'We needed something with its own story. Moyee has that, and it tastes great too.'},
        ],
      },
      impact: { label: 'What your order does' },
      cta: {
        heading: 'Find out if Moyee fits your venue.',
        sub: 'Order a trial package — taste it yourself before you decide.',
        primary: 'Order a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  ngo: {
    key: 'ngo',
    title: "Impact NGO's & fondsen, Moyee",
    hero: {
      eyebrow: "Impact NGO's & fondsen",
      headline: ['Impact op papier.', 'Impact in je kop.'],
      subline: 'Voor organisaties die niet alleen praten over impact, maar het ook inkopen. Moyee is de koffie die de theorie in de praktijk brengt — elke dag, elke kop.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie kantoor of project',
    },
    story: {
      heading: 'Inkoop als impactmiddel',
      body: "Fondsen en NGO's werken aan eerlijkheid in de wereld. Die keuze stopt niet bij de deur van het kantoor. Moyee is gebouwd op hetzelfde principe: niemand achter laten. Onze Fairchain-aanpak zorgt dat boeren in Ethiopië en Kenia niet alleen telen, maar ook roosteren en verpakken. Ze verdienen aan het eindproduct. Dat heet systemische impact.",
      highlight: 'Traditionele koffieketens laten de marge achter in de rijke landen. Moyee draait dat om. Elke kilo die jij bestelt, houdt waarde in de producerende gemeenschap. Dat is precies de theorie van verandering die jullie ook toepassen. Geen donatie, maar een verdienmodel. Dat kun je uitleggen aan je board, je donateurs én je team.',
    },
    steps: [
      'Bereken hoeveel koffie jullie kantoor nodig heeft — ook voor evenementen en donateursbijeenkomsten',
      'Ontvang een Fairchain-impactoverzicht — geschikt voor jullie jaarverslag',
      'Koffie die het gesprek op gang brengt bij elke vergadering en elk bezoek',
    ],
    testimonials: {
      label: 'Organisaties die je kent',
      heading: 'Impact organisaties die bewust inkopen',
      items: [
        {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
          quote:'Voor ons is Moyee geen inkoopdecisie maar een logische keuze. Elke kop koffie vertelt het verhaal van eerlijk ondernemen.'},
        {client:'Amnesty International NL',
          quote:'Moyee past bij onze waarden. Niet omdat we het moeten uitleggen, maar omdat het systeem klopt.'},
        {client:'Oxfam Novib',
          quote:'Als we het hebben over eerlijke ketens, moeten we dat ook in onze eigen inkoop terugzien. Moyee maakt dat mogelijk.'},
      ],
    },
    impact: { label: 'Directe impact van jouw bestelling' },
    cta: {
      heading: 'Laat je inkoop aansluiten bij je missie.',
      sub: 'Ontvang een proefpakket en een impactoverzicht voor je jaarverslag.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: "Impact NGOs & foundations, Moyee",
      hero: {
        eyebrow: "Impact NGOs & foundations",
        headline: ['Impact on paper.', 'Impact in your cup.'],
        subline: 'For organisations that not only talk about impact, but also procure it. Moyee is the coffee that puts theory into practice — every day, every cup.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office or project here',
      },
      story: {
        heading: 'Procurement as an impact tool',
        body: 'Foundations and NGOs work on fairness in the world. That choice does not stop at the office door. Moyee is built on the same principle: leave no one behind. Our Fairchain approach ensures that farmers in Ethiopia and Kenya do not just grow, but also roast and package. They earn from the end product. That is systemic impact.',
        highlight: 'Traditional coffee chains leave the margin in wealthy countries. Moyee reverses that. Every kilo you order keeps value in the producing community. That is exactly the theory of change you apply too. Not a donation, but a business model. You can explain that to your board, your donors and your team.',
      },
      steps: [
        'Calculate how much coffee your office needs — including events and donor gatherings',
        'Receive a Fairchain impact overview — suitable for your annual report',
        'Coffee that sparks the conversation at every meeting and every visit',
      ],
      testimonials: {
        label: 'Organisations you know',
        heading: 'Impact organisations that procure consciously',
        items: [
          {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
            quote:'For us, Moyee is not a procurement decision but a logical choice. Every cup tells the story of fair business.'},
          {client:'Amnesty International NL',
            quote:'Moyee fits our values. Not because we have to explain it, but because the system works.'},
          {client:'Oxfam Novib',
            quote:'When we talk about fair chains, we need to see that in our own procurement too. Moyee makes that possible.'},
        ],
      },
      impact: { label: 'Direct impact of your order' },
      cta: {
        heading: 'Let your procurement align with your mission.',
        sub: 'Receive a trial package and an impact overview for your annual report.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },
};

window.PAGE_DATA = PAGE_DATA;
