// Per-page content registry. Each entry feeds the LandingPage sections.
// Each page has an `en` block with English overrides (merged over the Dutch base).

const PAGE_DATA = {
  bcorp: {
    key: 'bcorp',
    title: 'B-Corps & ESG-kantoren, Moyee',
    hero: {
      eyebrow: 'B-Corp & ESG-kantoren',
      headline: ['Jij bent gecertificeerd.', 'Je koffie ook.'],
      subline: 'Gewone koffie laat 10% van de waarde achter in het productieland. Moyee laat 50% achter, geboerd, gebrand én verpakt in Ethiopië en Kenia. Geen claim maar een businessmodel, en aantoonbaar in je ESG-rapport.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep hier een foto van je kantoor / impact-rapport',
    },
    story: {
      heading: 'Van Fairchain naar jouw jaarverslag',
      body: 'B-Corp vraagt om keuzes in de hele keten, ook in je inkoop. Moyee bóuwt die keten zelf: elke kilo maakt werk, kennis en inkomen in Ethiopië en Kenia. Wij betaalden leefbaar inkomen en brandden aan de bron al in 2012, toen niemand het erover had. Geen donatie, een verdienmodel. Dat heet Fairchain.',
      highlight: 'Gewone koffie wordt elders gebrand, zodat marge én kennis bij de groothandel blijven. Bij Moyee gebeurt alles in het productieland, en elke kilo die je team drinkt haalt 49 kg CO₂ uit de lucht. Geen footprint maar een handprint. Dat vertellen we niet, dat bewijzen we: in cijfers die je zo in je rapportage zet.',
    },
    steps: [
      'Bereken hoeveel koffie jullie team nodig heeft en kies je blend',
      'Koffie wordt gebrand in Ethiopië of Kenia, direct naar jullie kantoor',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Klanten die je herkent',
      heading: 'Organisaties met dezelfde standaard',
      items: [
        {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
          quote:'Voor ons is Moyee geen inkoopdecisie maar een logische keuze. Elke kop koffie vertelt het verhaal van ondernemen dat klopt.'},
        {client:'ASR', logo:'assets/clients/asr.png',
          quote:'We wilden als verzekeraar in onze inkoop aantonen dat impact en kwaliteit hand in hand gaan. Moyee is daarin vanzelfsprekend.'},
        {client:'Amnesty International NL',
          quote:'Moyee past bij onze waarden. Niet omdat we het moeten uitleggen, maar omdat het systeem klopt.'},
      ],
    },
    impact: { label: 'Impact per bestelling' },
    cta: {
      heading: 'Klaar om Moyee aan je ESG-dossier toe te voegen?',
      sub: 'Ontvang een proefpakket en een impactoverzicht voor je rapportage.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'B-Corps & ESG offices, Moyee',
      hero: {
        eyebrow: 'B-Corp & ESG offices',
        headline: ["You're certified.", 'Your coffee too.'],
        subline: 'Ordinary coffee leaves 10% of the value in the country of origin. Moyee leaves 50%, farmed, roasted and packaged in Ethiopia and Kenya. Not a claim but a business model, and demonstrable in your ESG report.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office / impact report here',
      },
      story: {
        heading: 'From Fairchain to your annual report',
        body: 'B-Corp requires choices throughout the chain, procurement included. Moyee builds that chain itself: every kilo creates work, knowledge and income in Ethiopia and Kenya. We paid living incomes and roasted at origin back in 2012, when no one was talking about it. Not a donation, a business model. That is called Fairchain.',
        highlight: 'Ordinary coffee is roasted elsewhere, so margin and expertise stay with wholesalers. At Moyee everything happens in the country of origin, and every kilo your team drinks removes 49 kg of CO₂ from the air. Not a footprint but a handprint. We do not tell that story, we prove it: in numbers you can drop straight into your reporting.',
      },
      steps: [
        'Calculate how much coffee your team needs and choose your blend',
        'Coffee is roasted in Ethiopia or Kenya, delivered directly to your office',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Clients you recognise',
        heading: 'Organisations with the same standard',
        items: [
          {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
            quote:'For us, Moyee is not a procurement decision but a logical choice. Every cup tells the story of business that holds up.'},
          {client:'ASR', logo:'assets/clients/asr.png',
            quote:'As an insurer, we wanted our procurement to prove that impact and quality go hand in hand. Moyee is the obvious answer.'},
          {client:'Amnesty International NL',
            quote:'Moyee fits our values. Not because we have to explain it, but because the system works.'},
        ],
      },
      impact: { label: 'Impact per order' },
      cta: {
        heading: 'Ready to add Moyee to your ESG dossier?',
        sub: 'Receive a trial package and an impact overview for your report.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  tech: {
    key: 'tech',
    title: 'Tech scale-ups & People and Culture, Moyee',
    hero: {
      eyebrow: 'Tech scale-ups & People and Culture',
      headline: ['Je hebt overal over nagedacht.', 'Nu de koffie.'],
      subline: 'Je bouwt een bedrijf waar mensen graag werken. De koffie in de keuken is geen bijzaak. Het is een eerste indruk, elke ochtend opnieuw.',
      ctaPrimary: 'Stuur ons een proefpakket',
      imagePlaceholder: 'Sleep een foto van jullie kantoorkeuken / team',
    },
    story: {
      heading: 'Koffie die je team iets te vertellen heeft',
      body: 'Moyee is gebouwd op een idee dat je team meteen snapt: wat als je de keten niet inkoopt maar zélf bent? Geboerd, gebrand en verpakt in Ethiopië en Kenia, met 50% van de waarde die aan de bron blijft in plaats van 10%. Dat verhaal gaat vanzelf rond op kantoor, niet omdat je het uitlegt, maar omdat het op de verpakking staat.',
      highlight: 'Fairchain betekent: geboerd, gebrand en verpakt in het productieland, met leefbaar inkomen voor de boer sinds 2012. Minder tussenschakels, meer waarde voor de mensen achter de boon. Elke kop die je team drinkt haalt bovendien 49 kg CO₂ uit de lucht. Dat is het soort detail dat blijft hangen, en waar nieuwe mensen naar vragen.',
    },
    steps: [
      'Bereken hoeveel koffie jullie team verbruikt, de calculator doet het werk',
      'Kies een blend die past bij hoe jullie werken: sterk voor lange dagen, licht voor de loop',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Bedrijven die je kent',
      heading: 'Scale-ups die al voor Moyee kozen',
      items: [
        {client:'Dynalogic', logo:'assets/clients/dynalogic.png',
          quote:'Onze keuken is de plek waar alles begint. Nu begint het met koffie die ergens voor staat.'},
        {client:'Highberg Digital',
          quote:'Nieuw teamlid vroeg meteen waar de koffie vandaan komt. Dat is precies de reden waarom we Moyee hebben.'},
        {client:'Rapid Circle',
          quote:'Fijn dat het gewoon geregeld is. En dat er ook nog iets achter zit.'},
      ],
    },
    impact: { label: 'Impact per bestelling' },
    cta: {
      heading: 'Stuur je team een proefpakket.',
      sub: 'Geen verplichtingen. Wel een verhaal voor in de keuken.',
      primary: 'Stuur ons een proefpakket',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Tech scale-ups & People and Culture, Moyee',
      hero: {
        eyebrow: 'Tech scale-ups & People and Culture',
        headline: ["You've thought of everything.", 'Now the coffee.'],
        subline: "You're building a company people love to work at. The coffee in the kitchen is not a side issue. It's a first impression, every morning.",
        ctaPrimary: 'Send us a trial package',
        imagePlaceholder: 'Drop a photo of your office kitchen / team here',
      },
      story: {
        heading: 'Coffee your team has something to talk about',
        body: "Moyee is built on an idea your team will get right away: what if you do not buy the supply chain but are it? Farmed, roasted and packaged in Ethiopia and Kenya, with 50% of the value staying at origin instead of 10%. That story spreads around the office on its own, not because you explain it, but because it says so on the packaging.",
        highlight: 'Fairchain means: farmed, roasted and packaged in the country of origin, with a living income for the farmer since 2012. Fewer intermediaries, more value for the people behind the bean. Every cup your team drinks also removes 49 kg of CO₂ from the air. That is the kind of detail that sticks, and that new hires ask about.',
      },
      steps: [
        'Calculate how much coffee your team uses, the calculator does the work',
        'Choose a blend that fits how you work: strong for long days, light for the flow',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Companies you know',
        heading: 'Scale-ups that already chose Moyee',
        items: [
          {client:'Dynalogic', logo:'assets/clients/dynalogic.png',
            quote:'Our kitchen is where everything starts. Now it starts with coffee that stands for something.'},
          {client:'Highberg Digital',
            quote:'New team member immediately asked where the coffee comes from. That is exactly why we have Moyee.'},
          {client:'Rapid Circle',
            quote:'Great that it is just sorted. And that there is something behind it too.'},
        ],
      },
      impact: { label: 'Impact per order' },
      cta: {
        heading: 'Send your team a trial package.',
        sub: 'No commitments. But there is a story for the kitchen.',
        primary: 'Send us a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  creative: {
    key: 'creative',
    title: 'Creatieve agencies, Moyee',
    hero: {
      eyebrow: 'Creatieve agencies',
      headline: ['Jullie verkopen verhalen.', 'Dit is een hele goeie.'],
      subline: 'Moyee draaide het systeem achter koffie volledig om: niet de keten inkopen, maar de keten zíjn. Van boer tot beker, alles anders. Precies het soort verhaal waar jullie van houden, en dit klopt tot op de cent.',
      ctaPrimary: 'Bestel een proefpakket',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie studio',
    },
    story: {
      heading: 'Een merk dat staat voor iets, net als jullie',
      body: 'Wij noemen het Fairchain. Geen marketingterm, een model. We kopen niet van de keten, we zíjn de keten. Geboerd, gebrand en verpakt in Ethiopië en Kenia, met 50% van de waarde aan de bron in plaats van 10%. De designers, branders en logistici daar verdienen een leefbaar inkomen. En jij krijgt koffie met een verhaal dat je zelf niet beter had kunnen verzinnen, en dat we kunnen bewijzen.',
      highlight: 'Goede bureaus weten: het product is het verhaal. Bij Moyee is het omgekeerde ook waar, het verhaal ís het product. We doen niet aan story telling maar aan story proving: elke kop haalt 49 kg CO₂ uit de lucht, elke boer krijgt leefbaar inkomen sinds 2012. Niet als toevoeging, maar als kern. Dat herkennen jullie.',
    },
    steps: [
      'Kies een blend die past bij de sfeer van jullie kantoor',
      'Levering aan jullie studio, maandelijks, geen gedoe',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Studios en bureaus die al voor Moyee kozen',
      heading: 'Bureaus die het verhaal verstaan',
      items: [
        {client:'Pllek Amsterdam',
          quote:'Gasten vragen er altijd naar. Dat is het beste compliment dat je kunt krijgen voor een koffiekeuze.'},
        {client:'Conscious Hotel',
          quote:'Moyee past bij hoe we over alles nadenken. Niet als toevoeging, maar als standaard.'},
        {client:'Brood Café',
          quote:'We hadden iets nodig met een eigen verhaal. Moyee heeft dat, en het smaakt ook nog eens goed.'},
      ],
    },
    impact: { label: 'De getallen achter het verhaal' },
    cta: {
      heading: 'Een proefpakket zegt meer dan een pitch.',
      sub: 'Laat het verhaal voor zichzelf spreken. Wij sturen het op.',
      primary: 'Bestel een proefpakket',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Creative agencies, Moyee',
      hero: {
        eyebrow: 'Creative agencies',
        headline: ['You sell stories.', 'This is a good one.'],
        subline: 'Moyee flipped the coffee system completely: not buying the chain, but being it. From farm to cup, everything different. Exactly the kind of story you love, and this one holds up to the cent.',
        ctaPrimary: 'Order a trial package',
        imagePlaceholder: 'Drop an atmosphere photo of your studio here',
      },
      story: {
        heading: 'A brand that stands for something, just like you',
        body: "We call it Fairchain. Not a marketing term, a model. We do not buy from the chain, we are the chain. Farmed, roasted and packaged in Ethiopia and Kenya, with 50% of the value staying at origin instead of 10%. The designers, roasters and logistics staff there earn a living income. And you get coffee with a story you could not have invented better yourself, and that we can prove.",
        highlight: "Good agencies know: the product is the story. At Moyee the reverse is also true, the story is the product. We do not do story telling but story proving: every cup removes 49 kg of CO₂ from the air, every farmer has earned a living income since 2012. Not as an add-on, but at the core. You recognise that.",
      },
      steps: [
        'Choose a blend that fits the atmosphere of your studio',
        'Delivery to your studio, monthly, no hassle',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Studios and agencies that already chose Moyee',
        heading: 'Agencies that get the story',
        items: [
          {client:'Pllek Amsterdam',
            quote:'Guests always ask about it. That is the best compliment you can get for a coffee choice.'},
          {client:'Conscious Hotel',
            quote:"Moyee fits how we think about everything. Not as an add-on, but as the standard."},
          {client:'Brood Café',
            quote:'We needed something with its own story. Moyee has that, and it tastes great too.'},
        ],
      },
      impact: { label: 'The numbers behind the story' },
      cta: {
        heading: 'A trial package says more than a pitch.',
        sub: "Let the story speak for itself. We'll send it over.",
        primary: 'Order a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  professional: {
    key: 'professional',
    title: 'Professional services, Moyee',
    hero: {
      eyebrow: 'Professional services',
      headline: ['Integriteit zit in de details.', 'Inclusief de koffie.'],
      subline: 'Voor kantoren die hoge standaarden gewend zijn, ook voor wat er op tafel staat als de klant binnenkomt.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een foto van jullie kantoor / ontvangst',
    },
    story: {
      heading: 'Koffie die past bij hoe jij je werk doet',
      body: 'Moyee maakt de koffieketen volledig traceerbaar: van boer tot factuur, leefbaar beloond, van begin tot eind. 50% van de waarde blijft aan de bron, tegen 10% in de gewone keten. Als je elke dag werkt aan precisie en standaarden voor anderen, past Moyee bij hoe jij je kantoor runt. Niet als statement, maar als logische consequentie.',
      highlight: 'Fairchain is geen label maar een model. Elke kilo wordt geproduceerd, gebrand en verpakt in het land van herkomst, geen tussenschakels die de waarde afromen. Leefbaar inkomen voor de boer sinds 2012, traceerbaar tot de coöperatie voor jou, specialty-grade in de kop. Dat is het soort keuze waar je geen tweede keer over hoeft na te denken.',
    },
    steps: [
      'Bereken hoeveel koffie jullie kantoor maandelijks verbruikt',
      'Kies een blend, specialty niveau, voor de klant aan tafel en de vergadering erna',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Kantoren die al voor Moyee kozen',
      heading: 'Kantoren met dezelfde standaard',
      items: [
        {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
          quote:'We wilden iets dat past bij hoe we over verantwoord beleggen denken. Moyee sloot daarop aan.'},
        {client:'AXA', logo:'assets/clients/axa.png',
          quote:'Als internationaal bedrijf letten we op elke keuze. Moyee past bij hoe wij omgaan met kwaliteit én maatschappelijke verantwoordelijkheid.'},
        {client:'BVDV Advocaten',
          quote:'Klanten vragen er soms naar als ze de verpakking zien. Dan kun je even iets vertellen.'},
      ],
    },
    impact: { label: 'De feiten' },
    cta: {
      heading: 'Ontvang een proefpakket voor het kantoor.',
      sub: 'Geen verplichtingen. Gewoon koffie, met een verhaal om bij te bewaren.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Professional services, Moyee',
      hero: {
        eyebrow: 'Professional services',
        headline: ['Integrity is in the details.', 'Including the coffee.'],
        subline: "For offices accustomed to high standards, even in what's on the table when a client walks in.",
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office / reception here',
      },
      story: {
        heading: 'Coffee that fits how you do your work',
        body: 'Moyee makes the coffee chain fully traceable: from farm to invoice, paid a living income, from start to finish. 50% of the value stays at origin, against 10% in the ordinary chain. If you work every day on precision and standards for others, Moyee fits how you run your office. Not as a statement, but as a logical consequence.',
        highlight: 'Fairchain is not a label but a model. Every kilo is produced, roasted and packaged in the country of origin, no intermediaries skimming the value. A living income for the farmer since 2012, traceable to the cooperative for you, specialty-grade in the cup. That is the kind of choice you do not have to think twice about.',
      },
      steps: [
        'Calculate how much coffee your office uses monthly',
        'Choose a blend, specialty level, for the client at the table and the meeting after',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Offices that already chose Moyee',
        heading: 'Offices with the same standard',
        items: [
          {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
            quote:'We wanted something that fits how we think about responsible investing. Moyee matched that.'},
          {client:'AXA', logo:'assets/clients/axa.png',
            quote:'As an international company we pay attention to every choice. Moyee fits how we handle quality and social responsibility.'},
          {client:'BVDV Advocaten',
            quote:'Clients sometimes ask about it when they see the packaging. Then you can say something.'},
        ],
      },
      impact: { label: 'The facts' },
      cta: {
        heading: 'Receive a trial package for the office.',
        sub: 'No obligations. Just coffee, with a story worth keeping.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  cowork: {
    key: 'cowork',
    title: 'Cowork & flexkantoren, Moyee',
    hero: {
      eyebrow: 'Cowork & flexkantoren',
      headline: ['Jouw leden verwachten het beste.', 'Ook van de koffie.'],
      subline: 'Eén contract, honderden gebruikers. Moyee levert specialty koffie die jouw community iets geeft om over te praten, met een verhaal dat past bij waarom ze hier werken.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie coworkruimte',
    },
    story: {
      heading: 'Koffie die de community bouwt',
      body: 'Een coworkspace is meer dan bureaus en wifi. Het gevoel begint bij de koffie. Moyee brengt specialty kwaliteit én een verhaal dat leden direct herkennen: geboerd, gebrand en verpakt aan de bron, met 50% van de waarde die daar blijft in plaats van 10%. Dat is iets om trots op te zijn, en om te delen.',
      highlight: 'Fairchain betekent dat elke kilo wordt geboerd, gebrand en verpakt in het productieland, leefbaar inkomen voor de boer sinds 2012, en 49 kg CO₂ uit de lucht per kilo. Geen verspilde marge aan tussenschakels. Jij biedt je leden een product dat verhalen opwekt. Dat is het verschil tussen koffie als bijzaak en koffie als deel van je merk.',
    },
    steps: [
      'Bereken hoeveel koffie jouw space maandelijks nodig heeft, we helpen rekenen',
      'Één levering, één factuur, ook bij meerdere vestigingen',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Spaces die al voor Moyee kozen',
      heading: 'Communities die het verschil proeven',
      items: [
        {client:'Spaces Amsterdam',
          quote:'Leden merken de kwaliteit meteen. En als ze vragen waar het vandaan komt, hebben we een goed verhaal.'},
        {client:'B. Amsterdam',
          quote:'In een community draait alles om sfeer en gevoel. Moyee draagt daarin bij, elke dag opnieuw.'},
        {client:'Tribes Utrecht',
          quote:'Het gaat verder dan koffie. Het is een keuze die zegt: we denken na over alles wat we hier neerzetten.'},
      ],
    },
    impact: { label: 'Impact per bestelling' },
    cta: {
      heading: 'Zet Moyee neer in jouw space.',
      sub: 'Vraag een proefpakket aan, wij zorgen voor de rest.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Cowork & flex offices, Moyee',
      hero: {
        eyebrow: 'Cowork & flex offices',
        headline: ['Your members expect the best.', 'Including the coffee.'],
        subline: 'One contract, hundreds of users. Moyee delivers specialty coffee that gives your community something to talk about, with a story that fits why they work here.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop an atmosphere photo of your cowork space here',
      },
      story: {
        heading: 'Coffee that builds community',
        body: 'A coworking space is more than desks and wifi. The feeling starts with the coffee. Moyee brings specialty quality and a story members recognise right away: farmed, roasted and packaged at origin, with 50% of the value staying there instead of 10%. That is something to be proud of, and to share.',
        highlight: 'Fairchain means every kilo is farmed, roasted and packaged in the country of origin, a living income for the farmer since 2012, and 49 kg of CO₂ removed from the air per kilo. No wasted margin on intermediaries. You offer your members a product that sparks conversations. That is the difference between coffee as an afterthought and coffee as part of your brand.',
      },
      steps: [
        'Calculate how much coffee your space needs monthly, we help with the maths',
        'One delivery, one invoice, even across multiple locations',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Spaces that already chose Moyee',
        heading: 'Communities that taste the difference',
        items: [
          {client:'Spaces Amsterdam',
            quote:'Members notice the quality right away. And when they ask where it comes from, we have a great story.'},
          {client:'B. Amsterdam',
            quote:'In a community everything is about atmosphere and feeling. Moyee contributes to that, every day.'},
          {client:'Tribes Utrecht',
            quote:'It goes beyond coffee. It is a choice that says: we think carefully about everything we put here.'},
        ],
      },
      impact: { label: 'Impact per order' },
      cta: {
        heading: 'Put Moyee in your space.',
        sub: 'Request a trial package, we take care of the rest.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  finance: {
    key: 'finance',
    title: 'Verzekeraars & financiële dienstverleners, Moyee',
    hero: {
      eyebrow: 'Verzekeringen & financiële dienstverlening',
      headline: ['Duurzaam beleggen.', 'Fairchain in de kop.'],
      subline: 'Financiële instellingen staan steeds vaker voor de vraag: klopt onze eigen inkoop bij wat we uitdragen? Moyee is de koffie waarbij het antwoord ja is.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een foto van jullie kantoor / boardroom',
    },
    story: {
      heading: 'Inkoop die klopt bij jullie ESG-raamwerk',
      body: 'Banken, verzekeraars en vermogensbeheerders stellen strengere eisen aan hun eigen leveranciers. Moyee voldoet daaraan niet als certificeringsstrategie, maar omdat het model van begin tot eind controleerbaar is: 50% van de waarde blijft aan de bron tegen 10% in de gewone keten, leefbaar inkomen sinds 2012. Van boer tot factuur, alles aantoonbaar.',
      highlight: 'Fairchain is geen label maar een model. Elke kilo wordt geproduceerd, gebrand en verpakt in het productieland; de marges blijven in de keten waar ze horen en elke kilo haalt 49 kg CO₂ uit de lucht. Jij kunt dat aantonen: in het leveranciersregister, in de jaarrekening, aan toezichthouders.',
    },
    steps: [
      'Bereken jullie verbruik, geschikt voor kleine teams én grote kantoorlocaties',
      'Ontvang een Fairchain-impactoverzicht voor jullie leveranciersdossier',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Organisaties die je kent',
      heading: 'Financiële dienstverleners die bewust kozen',
      items: [
        {client:'ASR', logo:'assets/clients/asr.png',
          quote:'We wilden als verzekeraar in onze inkoop aantonen dat impact en kwaliteit samengaan. Moyee is daarin vanzelfsprekend.'},
        {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
          quote:'We wilden iets dat past bij hoe we over verantwoord beleggen denken. Moyee sloot daarop aan.'},
        {client:'AXA', logo:'assets/clients/axa.png',
          quote:'Als internationaal bedrijf letten we op elke keuze. Moyee past bij hoe wij omgaan met kwaliteit én maatschappelijke verantwoordelijkheid.'},
      ],
    },
    impact: { label: 'Aantoonbare impact per bestelling' },
    cta: {
      heading: 'Koffie die past in jullie leveranciersdossier.',
      sub: 'Ontvang een proefpakket en een impactoverzicht, geschikt voor ESG-rapportage.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Insurers & financial services, Moyee',
      hero: {
        eyebrow: 'Insurance & financial services',
        headline: ['Sustainable investing.', 'Fairchain in the cup.'],
        subline: 'Financial institutions increasingly face the question: does our own procurement match what we stand for? Moyee is the coffee where the answer is yes.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office / boardroom here',
      },
      story: {
        heading: 'Procurement that fits your ESG framework',
        body: 'Banks, insurers and asset managers set increasingly strict requirements on their own suppliers. Moyee meets them not as a certification strategy, but because the model is verifiable from start to finish: 50% of the value stays at origin against 10% in the ordinary chain, a living income since 2012. From farm to invoice, everything accountable.',
        highlight: 'Fairchain is not a label but a model. Every kilo is produced, roasted and packaged in the country of origin; margins stay in the chain where they belong and every kilo removes 49 kg of CO₂ from the air. You can demonstrate that: in the supplier register, in the annual report, to regulators.',
      },
      steps: [
        'Calculate your usage, suitable for small teams and large office locations',
        'Receive a Fairchain impact overview for your supplier dossier',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Organisations you know',
        heading: 'Financial services firms that chose consciously',
        items: [
          {client:'ASR', logo:'assets/clients/asr.png',
            quote:'As an insurer, we wanted our procurement to prove that impact and quality go hand in hand. Moyee is the obvious answer.'},
          {client:'Van Lanschot Kempen', logo:'assets/clients/van-lanschot.png',
            quote:'We wanted something that fits how we think about responsible investing. Moyee matched that.'},
          {client:'AXA', logo:'assets/clients/axa.png',
            quote:'As an international company we pay attention to every choice. Moyee fits how we handle quality and social responsibility.'},
        ],
      },
      impact: { label: 'Demonstrable impact per order' },
      cta: {
        heading: 'Coffee that fits your supplier dossier.',
        sub: 'Receive a trial package and an impact overview, suitable for ESG reporting.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  horeca: {
    key: 'horeca',
    title: 'Boutique HoReCa, Moyee',
    hero: {
      eyebrow: 'Boutique HoReCa',
      headline: ['Je gasten onthouden de koffie.', 'Geef ze een reden.'],
      subline: 'Voor onafhankelijke cafés, boutique hotels en restaurants die bewust kiezen wat er op tafel staat en dat verhaal kunnen vertellen.',
      ctaPrimary: 'Bestel een proefpakket',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie zaak',
    },
    story: {
      heading: 'Koffie die onderdeel wordt van jouw verhaal',
      body: 'Boutique horeca onderscheidt zich niet op grootte, maar op karakter. Elke keuze, van meubels tot muziek, vertelt wie je bent. Moyee past in dat plaatje: specialty-grade koffie, traceerbaar tot de coöperatie, met 50% van de waarde die aan de bron blijft in plaats van 10%. Gasten proeven het verschil. En ze komen terug.',
      highlight: 'Fairchain: geboerd, gebrand en verpakt in Ethiopië of Kenia. Geen tussenhandel, geen onbekende herkomst, leefbaar inkomen voor de boer sinds 2012 en 49 kg CO₂ uit de lucht per kilo. Als een gast vraagt waar de koffie vandaan komt, geef jij het hele verhaal. Dat is het gesprek dat jou onderscheidt van de keten om de hoek.',
    },
    steps: [
      'Kies een blend die past bij jouw zaak: van licht en fruitig tot donker en intens',
      'Levering op jouw planning: per week, per twee weken of maandelijks',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Zaken die al voor Moyee kozen',
      heading: 'Horeca die kwaliteit én verhaal serieus neemt',
      items: [
        {client:'Pllek Amsterdam',
          quote:'Gasten vragen er altijd naar. Dat is het beste compliment dat je kunt krijgen voor een koffiekeuze.'},
        {client:'Conscious Hotel',
          quote:'Moyee past bij hoe we over alles nadenken. Niet als toevoeging, maar als standaard.'},
        {client:'Brood Café',
          quote:'We hadden iets nodig met een eigen verhaal. Moyee heeft dat, en het smaakt ook nog eens goed.'},
      ],
    },
    impact: { label: 'Wat jouw bestelling doet' },
    cta: {
      heading: 'Ontdek of Moyee bij jouw zaak past.',
      sub: 'Bestel een proefpakket, proef het zelf voordat je beslist.',
      primary: 'Bestel een proefpakket',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: 'Boutique HoReCa, Moyee',
      hero: {
        eyebrow: 'Boutique HoReCa',
        headline: ['Your guests remember the coffee.', 'Give them a reason.'],
        subline: 'For independent cafés, boutique hotels and restaurants that consciously choose what goes on the table and can tell that story.',
        ctaPrimary: 'Order a trial package',
        imagePlaceholder: 'Drop an atmosphere photo of your venue here',
      },
      story: {
        heading: 'Coffee that becomes part of your story',
        body: 'Boutique hospitality differentiates itself not on size, but on character. Every choice, from furniture to music, tells who you are. Moyee fits that picture: specialty-grade coffee, traceable to the cooperative, with 50% of the value staying at origin instead of 10%. Guests taste the difference. And they come back.',
        highlight: 'Fairchain: farmed, roasted and packaged in Ethiopia or Kenya. No middlemen, no unknown origin, a living income for the farmer since 2012 and 49 kg of CO₂ removed from the air per kilo. When a guest asks where the coffee comes from, you tell the whole story. That is the conversation that sets you apart from the chain around the corner.',
      },
      steps: [
        'Choose a blend that fits your venue: from light and fruity to dark and intense',
        'Delivery on your schedule: weekly, fortnightly or monthly',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Venues that already chose Moyee',
        heading: 'Hospitality that takes quality and story seriously',
        items: [
          {client:'Pllek Amsterdam',
            quote:'Guests always ask about it. That is the best compliment you can get for a coffee choice.'},
          {client:'Conscious Hotel',
            quote:"Moyee fits how we think about everything. Not as an add-on, but as the standard."},
          {client:'Brood Café',
            quote:'We needed something with its own story. Moyee has that, and it tastes great too.'},
        ],
      },
      impact: { label: 'What your order does' },
      cta: {
        heading: 'Find out if Moyee fits your venue.',
        sub: 'Order a trial package, taste it yourself before you decide.',
        primary: 'Order a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },

  ngo: {
    key: 'ngo',
    title: "Impact NGO's & fondsen, Moyee",
    hero: {
      eyebrow: "Impact NGO's & fondsen",
      headline: ['Impact op papier.', 'Impact in je kop.'],
      subline: 'Voor organisaties die niet alleen praten over impact, maar het ook inkopen. Moyee is de koffie die de theorie in de praktijk brengt. Elke dag, elke kop.',
      ctaPrimary: 'Vraag een proefpakket aan',
      imagePlaceholder: 'Sleep een sfeerfoto van jullie kantoor of project',
    },
    story: {
      heading: 'Inkoop als impactmiddel',
      body: "Fondsen en NGO's werken aan rechtvaardigheid in de wereld. Die keuze stopt niet bij de deur van het kantoor. Moyee is gebouwd op hetzelfde principe: niemand achterlaten. Onze Fairchain-aanpak zorgt dat boeren in Ethiopië en Kenia niet alleen telen, maar ook branden en verpakken, zo blijft 50% van de waarde aan de bron in plaats van 10%, met leefbaar inkomen sinds 2012. Dat heet systemische impact.",
      highlight: 'Traditionele koffieketens laten de marge achter in de rijke landen. Moyee draait dat om: elke kilo houdt waarde in de producerende gemeenschap én haalt 49 kg CO₂ uit de lucht, een handprint, geen footprint. Dat is precies de theory of change die jullie ook toepassen. Geen donatie, een verdienmodel. Dat leg je zo uit aan je board, je donateurs én je team.',
    },
    steps: [
      'Bereken hoeveel koffie jullie kantoor nodig heeft, ook voor evenementen en donateursbijeenkomsten',
      'Ontvang een Fairchain-impactoverzicht, geschikt voor jullie jaarverslag',
      'Ontvang specialty koffie voor een waanzinnige prijs',
    ],
    testimonials: {
      label: 'Organisaties die je kent',
      heading: 'Impact organisaties die bewust inkopen',
      items: [
        {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
          quote:'Voor ons is Moyee geen inkoopdecisie maar een logische keuze. Elke kop koffie vertelt het verhaal van ondernemen dat klopt.'},
        {client:'Amnesty International NL',
          quote:'Moyee past bij onze waarden. Niet omdat we het moeten uitleggen, maar omdat het systeem klopt.'},
        {client:'Oxfam Novib',
          quote:'Als we het hebben over ketens die kloppen, moeten we dat ook in onze eigen inkoop terugzien. Moyee maakt dat mogelijk.'},
      ],
    },
    impact: { label: 'Directe impact van jouw bestelling' },
    cta: {
      heading: 'Laat je inkoop aansluiten bij je missie.',
      sub: 'Ontvang een proefpakket en een impactoverzicht voor je jaarverslag.',
      primary: 'Vraag een proefpakket aan',
      secondary: 'Plan een kennismaking',
    },
    en: {
      title: "Impact NGOs & foundations, Moyee",
      hero: {
        eyebrow: "Impact NGOs & foundations",
        headline: ['Impact on paper.', 'Impact in your cup.'],
        subline: 'For organisations that not only talk about impact, but also procure it. Moyee is the coffee that puts theory into practice. Every day, every cup.',
        ctaPrimary: 'Request a trial package',
        imagePlaceholder: 'Drop a photo of your office or project here',
      },
      story: {
        heading: 'Procurement as an impact tool',
        body: 'Foundations and NGOs work on justice in the world. That choice does not stop at the office door. Moyee is built on the same principle: leave no one behind. Our Fairchain approach ensures that farmers in Ethiopia and Kenya do not just grow, but also roast and package, so 50% of the value stays at origin instead of 10%, with a living income since 2012. That is systemic impact.',
        highlight: 'Traditional coffee chains leave the margin in wealthy countries. Moyee reverses that: every kilo keeps value in the producing community and removes 49 kg of CO₂ from the air, a handprint, not a footprint. That is exactly the theory of change you apply too. Not a donation, a business model. You can explain that to your board, your donors and your team.',
      },
      steps: [
        'Calculate how much coffee your office needs, including events and donor gatherings',
        'Receive a Fairchain impact overview, suitable for your annual report',
        'Receive specialty coffee at an unbeatable price',
      ],
      testimonials: {
        label: 'Organisations you know',
        heading: 'Impact organisations that procure consciously',
        items: [
          {client:'Leger des Heils', logo:'assets/clients/leger-des-heils.svg',
            quote:'For us, Moyee is not a procurement decision but a logical choice. Every cup tells the story of business that holds up.'},
          {client:'Amnesty International NL',
            quote:'Moyee fits our values. Not because we have to explain it, but because the system works.'},
          {client:'Oxfam Novib',
            quote:'When we talk about chains that hold up, we need to see that in our own procurement too. Moyee makes that possible.'},
        ],
      },
      impact: { label: 'Direct impact of your order' },
      cta: {
        heading: 'Let your procurement align with your mission.',
        sub: 'Receive a trial package and an impact overview for your annual report.',
        primary: 'Request a trial package',
        secondary: 'Schedule an intro call',
      },
    },
  },
};

window.PAGE_DATA = PAGE_DATA;
